version: "3"
services:
  cole-palmer:
    build: .
    container_name: cole_palmer
    user: ctf
    working_dir: /home/ctf
    entrypoint: /bin/sh -c "./ynetd -p 4020 /home/ctf/launch.sh"
    ports:
      - "4020:4020"
    read_only: true
