services:
  cheshire-cat-core:
    build:
      context: ./
    image: cheshire-cat-core
    container_name: cheshire-cat-core
    ports:
      - 1337:80
    environment:
      - TZ=${CCAT_TIMEZONE:-UTC}
      - CCAT_HTTPS_PROXY_MODE=true
      - CCAT_DEBUG=false
      - CCAT_CACHE_TYPE=file_system
    restart: unless-stopped
