version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4949:3000"
    environment:
      - NODE_ENV=production
    command: |
      sh -c "npm run build && npm start"
