version: "3"
services:
  level5-crypto:
    build: .
    container_name: level5-crypto
    user: ctf
    working_dir: /home/ctf
    entrypoint: /bin/sh -c "./ynetd -p 6969 /home/ctf/launch.sh"
    ports:
      - "6969:6969"
    read_only: true